### PR TITLE
#47 WIP wasm support

### PR DESCRIPTION
**Pull request by tversteeg**
Work in progress for WebAssembly support. It compiles at the moment but it's non-functional.

### CODE REVIEW

**Comment by tversteeg** [comment]
@emoon the WASM VM is throwing a panic on `time::precise_time_s` (in `KeyHandler::new`). Apparently this is not supported in WASM. Would it be fine if I would replace that code with the [instant library](https://github.com/sebcrozet/instant)?

**Comment by emoon** [comment]
@tversteeg sure as long as it provides the same functionality (and only has few/no dependencies) it's fine

**Comment by tversteeg** [comment]
I'm kind of stuck with this PR.

The problem is that HTML5 has its own event loop for drawing on the canvas using [`window.requestAnimationFrame(callback)`](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame). I can't figure out a way to tie this event loop with the user defined `while` loop rust_minifb uses.
Normally I would maintain 2 threads and synchronize the buffer between them but that's not possible since WASM doesn't support threading yet.

I kind of need some help with this problem.
@FloVanGH?
@sinclairzx81?

**Comment by FloVanGH** [comment]
@tversteeg I had the same problem on OrbTk. Therefore I've created a Runner struct where you can define a custom loop for wasm. It is not the best code but at the moment it works. Maybe for wasm support you would provide a similar concept.

Wasm Runner:
https://gitlab.redox-os.org/redox-os/orbtk/blob/master/crates/shell/src/web/mod.rs#L224

Default Runner:
https://gitlab.redox-os.org/redox-os/orbtk/blob/master/crates/shell/src/web/mod.rs#L224

Winit solved that problem by using an event loop:

https://github.com/rust-windowing/winit/blob/master/examples/window.rs

**Comment by sinclairzx81** [comment]
@tversteeg Hi,

Thanks for the mention. To be honest, I am not too clued up on the best approach to take here that would align with the current `while(window.is_open()) {}` loop given current browser capabilities, but I think @FloVanGH ' s suggestion seems like a pretty good one. Having the JavaScript host call into the WASM context on `requestAnimationFrame(...)` with the `window.request_animation_frame(move |window| {... window.update_with_buffer(..); })` closure invoked on each call seems like it would work quite well.

Just on the threading side; it might be possible to run minifb within a web worker at some point in the  future. Sadly I don't think this is quite ready for showtime as `SharedArrayBuffer` has been currently disabled in most browsers in response to [Spectre](https://meltdownattack.com/) and the only way i know would be to copy buffers across contexts (super slow). However, this functionality should land one day, and should (in theory at least) allow one to retain the `while` loop simplicity through the use of JS Atomics.

I've included some MDN links for `SharedArrayBuffer` and `Atomics` below for reference. Due to much of this functionality currently being disabled in most browsers, I believe it's still possible to experiment with the threading via NodeJS and its [worker_thread](https://nodejs.org/api/worker_threads.html) module which does allow for `SharedArrayBuffer` and `Atomics`, with perhaps [Atomics.wait](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Atomics/wait) and [Atomics.notify](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Atomics/notify) being of some use to help synchronize without explicitly needing to run as event driven closures. Will take some poking around to get it all to work, but would allow the WASM implementations of minifb to align with the Desktop implementations (and keep the 'write one, run everywhere' nature of minifb in check)

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Atomics
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer

Also, great work on the WASM support!

**Comment by tversteeg** [comment]
Thanks a lot both! That's really helpful. I don't think I'll have much time this weekend for it but I'll definitely take a good look next week.

**Comment by tversteeg** [comment]
@FloVanGH 
I've been taking a look at the code you supplied (sorry for being late, I was very busy), and that would entail that the whole `while` loop of minifb needs to be changed and put inside a closure right? I doubt that @emoon would want this because keeping the `while` loop seems to be one of the strong points of minifb.

**Comment by tversteeg** [comment]
I'm closing this PR. Unfortunately I can't find a solution where the current structure is maintained. If anyone has any hints or the SharedArrayBuffer from @sinclairzx81's comment is widely available I'll re-open it.

**Comment by emoon** [comment]
I see. That is too bad. Like I said if we could have a slightly different API when using WASM I'm open for that idea as well.

**Comment by FloVanGH** [comment]
@tversteeg I think I could help. But at the moment I have a lot to do on OrbTk. On my next free time slot I will try to help you with this or.

**Pull request closed without merging**
