### PR TITLE
Use xkbcommon's function to convert a keysym to a unicode point

### PR DESCRIPTION
**Pull request by nifker**
Removed key_mapping.rs => less code.

### CODE REVIEW

**Comment by nifker** [comment]
Im unsure if the code_point range check is neccessary or not. Ill take a look if it is.

**Comment by emoon** [comment]
Thanks!

**Comment by nifker** [comment]
@emoon Can you apply the change in my x11 branch too? (forgot to add the deps for x11)

**Comment by nifker** [comment]
@emoon this change could really be important.

**Comment by emoon** [comment]
Can you open a new PR for the fix?

**Pull request merged**
