### PR TITLE
[WIP] Physical Keys

### PR DESCRIPTION
**Pull request by nifker**
This will close https://github.com/emoon/rust_minifb/issues/112.

### CODE REVIEW

**Comment by nifker** [comment]
@emoon would be interested in feedback.

**Comment by emoon** [comment]
I think the code looks good.

**Comment by nifker** [comment]
I am unsure if it is better to convert the system-dependent keycodes to our abstracted scancodes, or just expose the pressed keys as system-dependent u32. Which one could convert themself using a library.

**Comment by emoon** [comment]
Sorry for the late update. I'm not sure either what is best here

**Comment by emoon** [comment]
Closing due to progress for a while. We can re-open this if this is still going to be done.

**Pull request closed without merging**
