### PR TITLE
WIP: Fix Redox port

### PR DESCRIPTION
**Pull request by FloVanGH**
Start to fix the redox port (work in progress).

### CODE REVIEW

**Comment by emoon** [comment]
Awesome! Thanks for doing this :)

**Comment by FloVanGH** [comment]
You welcome ;-).

**Comment by emoon** [comment]
Hey, what is the current state of this PR?

**Comment by FloVanGH** [comment]
I have a working fork for Redox, but the scaling stuff is not yet adjusted. I hope I can spent some time soon to complete it.

**Comment by emoon** [comment]
Alright. Thanks :)

**Comment by emoon** [comment]
@FloVanGH Hi, I just wonder if you intend to finish this PR or should it be closed?

**Comment by emoon** [comment]
Closing for now. We can re-open this if any progress is made

**Comment by FloVanGH** [comment]
Hi sorry for the delayed answer. Because of lack of time I cannot complete it now. But as soon a sit will change I will complete the PR. But you can keep it closed until then.

**Comment by emoon** [comment]
Awesome! Thanks for the reply :)

**Pull request closed without merging**
